version: '3.1'

services:
  frontend:
    restart: always
    build:
      context: frontend
      args:
        DOCKER_BACKEND_HOST: backend
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
    ports:
      - 3000:3000
    environment:
      BACKEND_HOST: backend
  backend:
    restart: always
    build:
      context: backend
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
    env_file: .env
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl